### ISSUE TITLE
Stripes in between the clouds and black stripes in the trees 

### ISSUE THREAD

**Issue by MuratovBaiel12** [huanghongxun/HMCL-PE#131]
hello, I have such a problem in minecraft in the clouds stripes and from afar trees with black stripes didn’t help me, I reinstalled, deleted the game folder, well, I’m waiting for help I can send you a screenshot if needed. 

**Smartphone (please complete the following information):**
 - Device: [mi 6 flagman]
 - OS: [Android 9]
 - Version [latest version]

**Comment by Umarbashir19** [comment]
Please download Link send me

**Comment by Umarbashir19** [comment]
Please New Updates FPS Up

**Comment by MuratovBaiel12** [comment]
https://github.com/huanghongxun/HMCL-PE/releases

**Comment by MuratovBaiel12** [comment]
I understand what the problem is the clouds are separated because i have android 9
