### ISSUE TITLE
Angle renderer Update

### ISSUE THREAD

**Issue by BLOODREDFF** [huanghongxun/HMCL-PE#135]
**Is your feature request related to a problem? Please describe.**
It's not a problem... Angle Renderer is a new renderer maked from pojav launcher. It allows to use GPU and CPU at same time. Also this renderer can hold some mods that can't use in Holy gl4es.

**Screenshot**
![Screenshot_2022-12-11-09-29-33-63_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/89779399/206885713-94345821-d4d7-407a-93c5-e7035bab8285.jpg)

**Comment by LegacyGamerHD** [comment]
were not pojav

**Comment by BLOODREDFF** [comment]
> were not pojav

Pojav launcher crashes while playing
