### ISSUE TITLE
Crashing when installing version

### ISSUE THREAD

**Issue by lgsanai** [huanghongxun/HMCL-PE#136]
**Describe the bug**
When I install hmcl it works I go inside and it opens but when I install version with optifine or without it crashes in middle of installing my device have 2gb ram 64 bit but it is said hmcl will work in it I really want to play it please fix it or give me solution please and I don't get log it just crashes no warning
**To Reproduce**

**Paste logs here**

<details>
<summary>log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [vivo y91c]
 - OS: [e.g. Android 8]

**Additional context**

**Comment by LegacyGamerHD** [comment]
Wait on foldcraft

**Comment by lgsanai** [comment]
What does that mean man
