### ISSUE TITLE
Game crashed with the ForgeRocks Mod

### ISSUE THREAD

**Issue by PayToUse** [huanghongxun/HMCL-PE#153]
**Describe the bug**
I just installed the ForgeRocks mod for the FarPlane2 mod and once i launched it, it crashed

**To Reproduce**
1. Go to the launcher
2. Enable the ForgeRocks mod
3. Launch the game
4. Wait... 
5. Error happens

**Paste logs here**

<details>
![Screenshot_20230128_164628_com tungsten hmclpe](https://user-images.githubusercontent.com/67496494/215256685-b0619aae-d927-4362-87aa-c6e4490f1d12.jpg)

</details>

<details>
[latest.log](https://github.com/huanghongxun/HMCL-PE/files/10526799/latest.log)

```
read the log and check the erro
```
</details>

**Expected behavior**
What i expect to happen is to work pretty fine with the ForgeRocks mod

**Screenshots**
Check the screenshot up

**Smartphone (please complete the following information):**
 - Device: HUAWEI Nova 9
 - OS: EMUI 12, Android 11
 - Version 22.8.30-dev

**Additional context**
There's no other context about the bug, hope it's fixed in the next update

**Comment by LegacyGamerHD** [comment]
I would not even bother it's a dead project
