### ISSUE TITLE
org.lwjgl.system.APIUtil:apiLog:76]: MemoryUtil allocator: StdlibAllocator

### ISSUE THREAD

**Issue by ZHYxulei** [huanghongxun/HMCL-PE#156]
错误日志，不知道为什么，玩了一周mc上不去了，因为机械动力换的openGL4.3，一周前好好的，今天就不能玩了，其他版本选openGL4.3也不能玩，求解答，日志在下面
[]()https://zhyxulei.github.io/debug-1.log
help me

**Comment by ZHYxulei** [comment]
刚发现不全，看下面这个[](https://zhyxulei.github.io/debug-1.log)

**Comment by ZHYxulei** [comment]
刚发现log不全，看这个[]()https://zhyxulei.github.io/debug-1.log

**Comment by root-S7** [comment]
检查启动器内存设置是不是加入了特殊字符串

**Comment by ZHYxulei** [comment]
> 检查启动器内存设置是不是加入了特殊字符串

并没有，我还重装过几次hmclpe

**Comment by ZHYxulei** [comment]
难道是因为没有libjemalloc.so吗，但为什么以前能用@huanghongxun @root-S7 @ShirosakiMio @Tungstend

**Comment by ZHYxulei** [comment]
为什么其他版本选openGL4.3也玩不了？

**Comment by ZHYxulei** [comment]
[net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
这应该很关键

**Comment by LegacyGamerHD** [comment]
这个项目被放弃去 https://github.com/FCL-Team/FoldCraftLauncher 

这有很多错误 foldcraft 将是它的替代品

**Comment by ZHYxulei** [comment]
> 这个项目被放弃去 https://github.com/FCL-Team/FoldCraftLauncher 
> 
> 这有很多错误 foldcraft 将是它的替代品 

有什么办法能用吗

**Comment by ZHYxulei** [comment]
> 这个项目被放弃去 https://github.com/FCL-Team/FoldCraftLauncher 
> 
> 这有很多错误 foldcraft 将是它的替代品 

现在还有办法用吗

**Comment by root-S7** [comment]
我不清楚你为啥说virgl不能使用，也行你用的是boat端的virgl那确实不能使用，只有pojav后端的virgl可以正常使用（也不是说boat后端的virgl一定不能使用你需要慢慢调整分辨率缩放才能正常使用）。还有你觉得是mod问题则应该先删掉所有mod看下能不能进入

**Comment by ZHYxulei** [comment]
> 整

以前virgl不用缩放就能用，这次怎么事？

**Comment by ZHYxulei** [comment]
> 使

我一起用100%的缩放

**Comment by root-S7** [comment]
看清楚在回复吧，我说的是boat后端的virgl。。。。指的不是pojav端端virgl

**Comment by ZHYxulei** [comment]
> 看清楚在回复吧，我说的是boat后端的virgl。。。。指的不是pojav端端virgl

我说的确定是boat的啊

**Comment by LegacyGamerHD** [comment]
> > 这个项目被放弃去 https://github.com/FCL-Team/FoldCraftLauncher
> > 这有很多错误 foldcraft 将是它的替代品
> 
> 有什么办法能用吗

遗憾的是，在完成之前没有估计的时间

**Comment by ZHYxulei** [comment]
> > > 这个项目被放弃去 https://github.com/FCL-Team/FoldCraftLauncher
> > > 这有很多错误 foldcraft 将是它的替代品
> > 
> > 有什么办法能用吗
> 
> 遗憾的是，在完成之前没有估计的时间

是不是有已经编译完的😵

**Comment by root-S7** [comment]
> > 看清楚在回复吧，我说的是boat后端的virgl。。。。指的不是pojav端端virgl
> 
> 我说的确定是boat的啊

boat后端virgl一直都有问题，我不晓得你为啥会说没问题
