### ISSUE TITLE
下载过慢

### ISSUE THREAD

**Issue by huangminzhe** [huanghongxun/HMCL-PE#162]
### 问题描述：
无论是手机还是电脑，下载速度总是很慢

### 希望的解决方案：
在 Github Releases 上上传文件(.apk)

**Comment by horizon86** [comment]
> ### 问题描述：
> 无论是手机还是电脑，下载速度总是很慢
> 
> ### 希望的解决方案：
> 在 Github Releases 上上传文件(.apk)

release有apk啊
