### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZHYxulei** [huanghongxun/HMCL-PE#168]
![Screenshot_20230312_002105.jpg](https://user-images.githubusercontent.com/99074127/224536468-cbbca5d2-23dc-4668-9826-1ab7b843b418.jpg)

帮忙看看
@huanghongxun @ShirosakiMio @Tungstend @Glavo

**Comment by ZHYxulei** [comment]
就微软登录有问题，其他没问题，服了

**Comment by yushijinhun** [comment]
> @yushijinhun @ShirosakiMio @Glavo @LegacyGamerHD @TSaltedfishKing @TSaltedfishKing @Tungstend @MioShirosaki @huanghongxun @MatheusTGamerPro 来看看啊

@ZHYxulei 不要在 issue 里乱 at 人，你这样做是非常不礼貌的。你发了这个 issue 之后项目维护者会收到邮件的，不需要你 at。

**Comment by TSaltedfishKing** [comment]
Haowei Wen

Maybe this repo is no longer maintained cause there's no any active maintainer, you should try to fix by yourself or choose another launcher, thanks.

P.S. Please don't mention just like at any body if they not very related.

Best regards
TSaltedfishKing

**Comment by ZHYxulei** [comment]
> Haowei Wen
> 
> Maybe this repo is no longer maintained cause there's no any active maintainer, you should try to fix by yourself or choose another launcher, thanks.
> 
> P.S. Please don't mention just like at any body if they not very related.
> 
> Best regards
> TSaltedfishKing
> 

thank you

**Comment by ZHYxulei** [comment]
![Screenshot_20230318_153103.jpg](https://user-images.githubusercontent.com/99074127/226091944-a1c577c9-88c6-4069-8f18-ff0ac6f39c02.jpg)

重新登陆就成这样了

**Comment by ZHYxulei** [comment]
问题解决了，微软账号的年龄要满18岁，调出生日期就行了
