### ISSUE TITLE
Can't launch versions above 1.19.2

### ISSUE THREAD

**Issue by ZaNYAshlin** [huanghongxun/HMCL-PE#181]
**Describe the bug**
Versions below 1.19.2 and 1.19.2 launched correctly but I can't launch any versions above 1.19.2

**To Reproduce**
1. Install 1.19.3 and above
2. Launch it

**Smartphone (please complete the following information):**
 - Device: Realme GT NEO 3T RMX3371 EU
 - OS: Android 13, RealmeUI 4.0
 - Version: 1.0.0

**Additional context**
I think that need to update lwjgl-glfw:
https://github.com/huanghongxun/HMCL-PE/issues/149

**Comment by root-S7** [comment]
pojav后端的去搬pojav启动器的即可，boat后端的内测群有修复的glfw.jar

**Comment by LegacyGamerHD** [comment]
ic an launch it just fine

**Comment by LegacyGamerHD** [comment]
go to https://github.com/FCL-Team/FoldCraftLauncher for a working launcher
