### ISSUE TITLE
1.12以上版本为什么启动不了

### ISSUE THREAD

**Issue by Ksamamlo** [huanghongxun/HMCL-PE#194]
![Screenshot_2023-06-11-14-54-49-193_com.tungsten.hmclpe.jpg](https://github.com/huanghongxun/HMCL-PE/assets/90137709/e3bacd37-bf10-43a5-a177-07cbede6ea7f)

**Comment by root-S7** [comment]
请更新启动器

**Comment by Ksamamlo** [comment]
> 请更新启动器

已经是最新版了

**Comment by root-S7** [comment]
这不是最新版，最新版都是2.0.6版本了，你这是22年8月左右版本

**Comment by root-S7** [comment]
https://cowtransfer.com/s/f46a252b8ac54b

**Comment by Ksamamlo** [comment]
> https://cowtransfer.com/s/f46a252b8ac54b
> 
> 卸载不保留应用任何数据并安装这个版本试试
可以了，感谢
