### ISSUE TITLE
做了个 Action ，自动构建仓库的最新版本提供下载

### ISSUE THREAD

**Issue by zkitefly** [huanghongxun/HMCL-PE#200]
[点击此处前往下载](https://github.com/zkitefly/HMCL-PE-1/releases/latest)

Action 同步上游代码，并自动构建最新的软件

**Comment by root-S7** [comment]
没必要加了，原作者以及基本确定不会再有大更新了，现在都去做FCL启动器了
目前这个2.0.6版本还存在皮肤站登录存在BUG，pojav后端待更新，按键视角跟随BUG...需要修复

**Comment by zkitefly** [comment]
ok
